FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/src
RUN make -j8

RUN mkdir -p /deps
RUN ldd /repo/src/primer3_core | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/src/primer3_core /repo/src/primer3_core
ENV LD_LIBRARY_PATH=/deps
